sudo: required

services:
  - docker

jobs:
  include:
    - stage: Build Vim inside a Docker container
      script:
        - make image
        - make install
        - test -x $HOME/.local/bin/vim
